export const PERMISSIONS = [
  'USER_ACCESS_READ',
  'USER_PROVISION',
  'USER_STATE_MANAGE',
  'ROLE_MANAGE',
  'PATIENT_ASSIGNMENT_MANAGE',
  'PRIVILEGED_IDENTITY_VERIFY',
  'PATIENT_PROFILE_READ',
  'PATIENT_PROFILE_UPDATE',
  'PATIENT_HOME_READ',
  'PATIENT_MONITORING_MANAGE',
  'PATIENT_SCHEDULE_READ',
  'PATIENT_ONBOARDING_READ',
  'PATIENT_ONBOARDING_UPDATE',
  'PATIENT_SAFETY_READ',
  'PATIENT_ASSESSMENT_READ',
  'PATIENT_ASSESSMENT_UPDATE',
  'PATIENT_ASSESSMENT_STAFF_CORRECT',
  'PATIENT_SUPPORT_READ',
  'PATIENT_SUPPORT_FEEDBACK',
  'PATIENT_PROGRESS_READ',
  'PATIENT_MONITORING_READ',
  'CLINICIAN_OVERVIEW_READ',
  'ENGAGEMENT_READ',
  'ENGAGEMENT_CASE_ACKNOWLEDGE',
  'ENGAGEMENT_CASE_OUTREACH',
  'TECHNICAL_FAILURE_READ',
  'ENGAGEMENT_TECHNICAL_OVERRIDE',
  'CLINICAL_REVIEW_READ',
  'CLINICAL_REVIEW_ACKNOWLEDGE',
  'SAFETY_CASE_READ',
  'SAFETY_CASE_ACKNOWLEDGE',
  'SAFETY_CASE_DISPOSITION',
  'ROUTING_CONFIG_READ',
  'ROUTING_CONFIG_EDIT',
  'ROUTING_TEST_RECORD',
  'ROUTING_CONFIG_ACTIVATE',
  'ADMIN_OVERVIEW_READ',
  'CONTENT_RESOURCE_READ',
  'CONTENT_RESOURCE_EDIT',
  'CONTENT_RESOURCE_APPROVE',
  'AUDIT_READ',
  'OPERATIONAL_INCIDENT_READ',
] as const;

export type Permission = (typeof PERMISSIONS)[number];
export type ApplicationRoleName =
  'PATIENT' | 'CLINICIAN' | 'ADMIN' | 'OPERATIONS';
export type WorkspaceName = 'PATIENT' | 'CLINICIAN' | 'ADMIN';
export type ScopeKind =
  'OWN_PATIENT' | 'ASSIGNED_PATIENTS' | 'ADMIN_OPERATIONAL';

export const ROLE_ACCESS: Record<
  ApplicationRoleName,
  {
    workspace: WorkspaceName;
    permissions: readonly Permission[];
    scope: ScopeKind;
  }
> = {
  PATIENT: {
    workspace: 'PATIENT',
    permissions: [
      'PATIENT_PROFILE_READ',
      'PATIENT_PROFILE_UPDATE',
      'PATIENT_HOME_READ',
      'PATIENT_MONITORING_READ',
      'PATIENT_MONITORING_MANAGE',
      'PATIENT_SCHEDULE_READ',
      'PATIENT_ONBOARDING_READ',
      'PATIENT_ONBOARDING_UPDATE',
      'PATIENT_SAFETY_READ',
      'PATIENT_ASSESSMENT_READ',
      'PATIENT_ASSESSMENT_UPDATE',
      'PATIENT_SUPPORT_READ',
      'PATIENT_SUPPORT_FEEDBACK',
      'PATIENT_PROGRESS_READ',
    ],
    scope: 'OWN_PATIENT',
  },
  CLINICIAN: {
    workspace: 'CLINICIAN',
    permissions: [
      'PATIENT_PROFILE_READ',
      'PATIENT_SCHEDULE_READ',
      'SAFETY_CASE_READ',
      'SAFETY_CASE_ACKNOWLEDGE',
      'SAFETY_CASE_DISPOSITION',
      'PATIENT_ASSESSMENT_STAFF_CORRECT',
      'PATIENT_MONITORING_READ',
      'CLINICIAN_OVERVIEW_READ',
      'ENGAGEMENT_READ',
      'ENGAGEMENT_CASE_ACKNOWLEDGE',
      'ENGAGEMENT_CASE_OUTREACH',
      'CLINICAL_REVIEW_READ',
      'CLINICAL_REVIEW_ACKNOWLEDGE',
    ],
    scope: 'ASSIGNED_PATIENTS',
  },
  ADMIN: {
    workspace: 'ADMIN',
    permissions: [
      'USER_ACCESS_READ',
      'USER_PROVISION',
      'USER_STATE_MANAGE',
      'ROLE_MANAGE',
      'PATIENT_ASSIGNMENT_MANAGE',
      'PRIVILEGED_IDENTITY_VERIFY',
      'ROUTING_CONFIG_READ',
      'ROUTING_CONFIG_EDIT',
      'ROUTING_TEST_RECORD',
      'ROUTING_CONFIG_ACTIVATE',
      'SAFETY_CASE_READ',
      'TECHNICAL_FAILURE_READ',
      'ENGAGEMENT_TECHNICAL_OVERRIDE',
      'ADMIN_OVERVIEW_READ',
      'CONTENT_RESOURCE_READ',
      'CONTENT_RESOURCE_EDIT',
      'CONTENT_RESOURCE_APPROVE',
      'AUDIT_READ',
      'OPERATIONAL_INCIDENT_READ',
    ],
    scope: 'ADMIN_OPERATIONAL',
  },
  OPERATIONS: {
    workspace: 'ADMIN',
    permissions: [
      'USER_ACCESS_READ',
      'TECHNICAL_FAILURE_READ',
      'ENGAGEMENT_TECHNICAL_OVERRIDE',
      'ADMIN_OVERVIEW_READ',
      'AUDIT_READ',
      'OPERATIONAL_INCIDENT_READ',
    ],
    scope: 'ADMIN_OPERATIONAL',
  },
};

export const PRIVILEGED_ROLES = new Set<ApplicationRoleName>([
  'CLINICIAN',
  'ADMIN',
  'OPERATIONS',
]);

export function isValidRoleWorkspace(
  role: ApplicationRoleName,
  workspace: WorkspaceName,
) {
  return ROLE_ACCESS[role].workspace === workspace;
}
