import type {
  SafetyOwnerRole,
  SafetyReasonCode,
  SafetySeverity,
} from '@aud-subjective/contracts';
import { SAFETY_REASON_CODES } from '@aud-subjective/contracts';

export { SAFETY_REASON_CODES };
export type { SafetyReasonCode };

export type SafetyDomain =
  | 'WITHDRAWAL_OR_MEDICAL'
  | 'SUICIDE_OR_SELF_HARM'
  | 'PREGNANCY'
  | 'OTHER_SUBSTANCE'
  | 'ROUTINE_MEDICAL_CONTEXT';

export type SafetyReasonPolicy = {
  domain: SafetyDomain;
  ownerRole: SafetyOwnerRole;
  severity: Exclude<SafetySeverity, 'S_NONE'>;
};

const medical = (
  severity: SafetyReasonPolicy['severity'],
): SafetyReasonPolicy => ({
  domain: 'WITHDRAWAL_OR_MEDICAL',
  ownerRole: 'MEDICAL_SAFETY_OWNER',
  severity,
});

const suicide = (
  severity: SafetyReasonPolicy['severity'],
): SafetyReasonPolicy => ({
  domain: 'SUICIDE_OR_SELF_HARM',
  ownerRole: 'BEHAVIORAL_HEALTH_SAFETY_OWNER',
  severity,
});

export const REASON_POLICY = {
  CURRENT_SEIZURE: medical('S0_EMERGENCY'),
  SEVERE_CONFUSION_OR_DISORIENTATION: medical('S0_EMERGENCY'),
  HALLUCINATIONS_WITH_DISORIENTATION: medical('S0_EMERGENCY'),
  DIFFICULTY_REMAINING_CONSCIOUS: medical('S0_EMERGENCY'),
  BREATHING_DIFFICULTY: medical('S0_EMERGENCY'),
  REPEATED_VOMITING_WITH_SEVERE_ILLNESS: medical('S0_EMERGENCY'),
  CURRENT_SUICIDE_ATTEMPT: suicide('S0_EMERGENCY'),
  CURRENT_SELF_HARM_MEDICAL_EMERGENCY: suicide('S0_EMERGENCY'),
  EXPLICIT_IMMEDIATE_SUICIDE_PLAN_AND_INTENT_TO_ACT_NOW:
    suicide('S0_EMERGENCY'),

  CSSRS_ITEM_4_POSITIVE: suicide('S1_URGENT'),
  CSSRS_ITEM_5_POSITIVE: suicide('S1_URGENT'),
  SUICIDAL_BEHAVIOR_PREVIOUS_3_MONTHS: suicide('S1_URGENT'),
  HALLUCINATIONS_AFTER_RECENT_REDUCTION: medical('S1_URGENT'),
  PRIOR_WITHDRAWAL_SEIZURE_OR_DELIRIUM_WITH_RECENT_OR_PLANNED_MAJOR_REDUCTION:
    medical('S1_URGENT'),
  RECENT_REDUCTION_TWO_OR_MORE_WITHDRAWAL_SYMPTOMS: medical('S1_URGENT'),
  RECENT_REDUCTION_TWO_OR_MORE_MAJOR_WITHDRAWAL_RISK_FACTORS:
    medical('S1_URGENT'),
  WITHDRAWAL_SYMPTOMS_WITH_OPIOID_OR_SEDATIVE_CONTEXT:
    medical('S1_URGENT'),

  CSSRS_ITEMS_1_TO_3_POSITIVE_WITHOUT_4_5: suicide('S2_PRIORITY'),
  RECENT_REDUCTION_ONE_WITHDRAWAL_SYMPTOM: medical('S2_PRIORITY'),
  RECENT_REDUCTION_ONE_MAJOR_RISK_FACTOR: medical('S2_PRIORITY'),
  PROLONGED_HEAVY_REGULAR_USE_WITH_PLANNED_MAJOR_REDUCTION:
    medical('S2_PRIORITY'),
  PRIOR_WITHDRAWAL_HISTORY_UNSURE: medical('S2_PRIORITY'),
  SEDATIVE_DEPENDENCE_UNSURE_DURING_PLANNED_REDUCTION:
    medical('S2_PRIORITY'),
  PREGNANT_OR_POSSIBLY_PREGNANT_WITH_CURRENT_ALCOHOL_USE: {
    domain: 'PREGNANCY',
    ownerRole: 'OBSTETRIC_MEDICAL_OWNER',
    severity: 'S2_PRIORITY',
  },
  SERIOUS_MEDICAL_CONDITION_WITH_PLANNED_MAJOR_REDUCTION:
    medical('S2_PRIORITY'),
  PRIOR_WITHDRAWAL_SEIZURE_OR_DELIRIUM_WITHOUT_CURRENT_REDUCTION:
    medical('S2_PRIORITY'),

  OTHER_SUBSTANCE_USE_WITHOUT_ACUTE_INTERACTION: {
    domain: 'OTHER_SUBSTANCE',
    ownerRole: 'MEDICAL_SAFETY_OWNER',
    severity: 'S3_ROUTINE',
  },
  STABLE_MEDICAL_CONDITION: {
    domain: 'ROUTINE_MEDICAL_CONTEXT',
    ownerRole: 'MEDICAL_SAFETY_OWNER',
    severity: 'S3_ROUTINE',
  },
  CLINICIAN_DIRECTED_SAFETY_REVIEW: {
    domain: 'ROUTINE_MEDICAL_CONTEXT',
    ownerRole: 'MEDICAL_SAFETY_OWNER',
    severity: 'S3_ROUTINE',
  },
} satisfies Record<SafetyReasonCode, SafetyReasonPolicy>;
